#!/usr/bin/env bash
# Build the External/linux-x64 native libraries PINS needs at runtime,
# WITHOUT the maintainer's Nextcloud bundle (whose share URL returns 503).
#
# Covers the libraries that are open source and shipped in this repo:
#   SOFA  (IAU astronomy library, 248 .c files under SOFA/SOFA/src)
#   NOVAS (USNO astrometry library, has its own Linux Makefile)
# plus symlinks to Ubuntu's cfitsio and libraw, which exist as versioned
# sonames only while PINS asks for the unversioned name.
#
# NOT covered: proprietary vendor camera SDKs (ASI, Atik, Altair, ToupTek...).
# Those are only needed for cameras attached through NINA's native SDK path.
# Gear driven through INDI does not need them: NINA.INDI has no DllLoader
# references and talks to indiserver over TCP.
#
# Usage:  ./build-external-x64.sh <publish-dir>

set -euo pipefail

PUBLISH="${1:?usage: $0 <publish-dir>}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT="$PUBLISH/External/linux-x64"

[[ -d "$PUBLISH" ]] || { echo "publish dir not found: $PUBLISH" >&2; exit 1; }

echo "repo:    $REPO"
echo "publish: $PUBLISH"
echo "target:  $EXT"
echo

mkdir -p "$EXT"/{SOFA,NOVAS,Cfitsio,Libraw}

echo "== SOFA =="
# t_sofa_c.c is the upstream test harness and includes <sofa.h> with angle
# brackets; it is not part of the library.
(
    cd "$REPO/SOFA/SOFA/src"
    mapfile -t srcs < <(ls *.c | grep -v '^t_sofa_c.c$')
    echo "   compiling ${#srcs[@]} sources"
    gcc -shared -fPIC -O2 -std=c99 -I. -o "$EXT/SOFA/libsofa_c.so" "${srcs[@]}" -lm
)
file -b "$EXT/SOFA/libsofa_c.so" | sed 's/^/   /'
# SOFA.cs P/Invokes these by EntryPoint; if they are absent the build is wrong.
for sym in iauDtf2d iauAtco13 iauEpv00; do
    if nm -D "$EXT/SOFA/libsofa_c.so" | awk -v s="$sym" '$2=="T" && $3==s {found=1} END{exit !found}'; then
        echo "   OK export $sym"
    else
        echo "   FAIL missing export $sym" >&2
        exit 1
    fi
done

echo
echo "== NOVAS =="
make -C "$REPO/NOVAS31" >/dev/null
cp "$REPO/NOVAS31/libnovas_c.so" "$EXT/NOVAS/"
# cio_ra.bin is generated by the Makefile and read at runtime.
[[ -f "$REPO/NOVAS31/cio_ra.bin" ]] && cp "$REPO/NOVAS31/cio_ra.bin" "$EXT/NOVAS/"
file -b "$EXT/NOVAS/libnovas_c.so" | sed 's/^/   /'

echo
echo "== System libs (symlinked, unversioned name) =="
link_system() {
    local want="$1" dir="$2"
    local path
    # Match the soname exactly up to its version suffix: a bare `grep libraw.so`
    # also matches libraw1394.so.11 and libraw_r.so.23 and would link the wrong
    # library. Anchor on "<name>.so" or "<name>.so.<n>" at a field boundary.
    # NOTE: no `exit` in awk -- quitting early closes the pipe and kills
    # `ldconfig -p` with SIGPIPE, which pipefail turns into a script abort.
    # Take the first match with a flag instead.
    path=$(ldconfig -p \
        | awk -v n="$want" '!done && ($1 == n || index($1, n ".") == 1) {print $NF; done=1}')
    if [[ -n "$path" ]]; then
        ln -sf "$path" "$EXT/$dir/$want"
        echo "   OK      $want -> $path"
    else
        echo "   MISSING $want (install it, or leave it: only needed for that feature)"
    fi
    return 0
}
link_system libcfitsio.so Cfitsio
link_system libraw.so     Libraw

echo
echo "== Optional: JPL ephemeris =="
# Arch-independent binary data, present in the bitbucket external submodule.
JPL="$REPO/NINA.Plugins/PolarAlignment/NINA.Plugins.PolarAlignment.Test/External/JPLEPH"
if [[ -f "$JPL" ]]; then
    cp "$JPL" "$PUBLISH/External/JPLEPH"
    echo "   OK copied JPLEPH ($(du -h "$JPL" | cut -f1))"
else
    echo "   absent; PINS logs 'Ephemeris file not found' and uses its fallback"
fi

echo
echo "== Result =="
find "$PUBLISH/External" -type f -o -type l | sort | sed 's/^/   /'
echo
echo "Done. Run PINS with $PUBLISH as the working directory."
